### ISSUE TITLE
EN Version of README.md

### ISSUE THREAD

**Issue by ThomasFis** [JustFxDev/Portable-Kanboard-and-Webserver#1]
Qucik translation of the readme file - feel free to use :-)

Gruss
Thomas
[README_EN.md](https://github.com/JustFxDev/Portable-Kanboard-and-Webserver/files/10768488/README_EN.md)

**Comment by JustFxDev** [comment]
Thanks again for your english version of the readme.

I've added it and made it the main readme.

Cheers, Fx
